apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "name" . }}
      annotations:
        checksum: {{ include (print $.Chart.Name "/templates/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: hello-world-nodejs
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                  name: {{ template "name" . }}
                  key: version
