apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "name" . }}
          servicePort: 80

