apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "name" . }}
  name: {{ template "name" . }}
spec:
  ports:
  - name: exposed-port
    port: 80
    targetPort: 8080
  selector:
    name: {{ template "name" . }}
